name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
  
    steps:
    - uses: actions/checkout@v3

    - run: echo "username ${{ vars.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}."
    
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3.0.0
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:0.1.0 --tag ${{ env.IMAGE_NAME }}:latest

    - name: Push the Docker image
      run: docker push --all-tags ${{ env.IMAGE_NAME }}
    
